version: "3"

services:
  nextjs:
    image: museon-fe
    container_name: museon-fe
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env.local
