name: Build
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Build
        run: CI=true yarn build
